config/routes.rb
Rails.application.routes.draw do
  
  get 'users/show'
  root 'homes#top'
  devise_for :users
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
       resource :favorites, only: [:create, :destroy]
      # 単数にすると、そのコントローラのidがリクエストに含まれなくなります。
      # 今回、いいねの詳細ページは作成しません。
      # favoritesのshowページが不要で、idの受け渡しも必要ないので、resourceとなっています。
       
       
       resources :post_comments, only: [:create, :destroy]
  end
    
  # resourcesメソッドは、ルーティングを一括して自動生成してくれます。一方、onlyは、生成するルーティングを限定するオプションです。
  # 画像投稿には、「新規投稿」「一覧」「詳細機能」「削除」しか使わないため、不要なルーティングが実行されないようにonlyを設定します。
  
  # 親のresourcesで指定したコントローラ名に、子のresourcesで指定したコントローラ名が続くURLが生成されるのが確認できます。
  # このような親子関係を、「ネストする」と言います。
  
   resources :users, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_image


end

app/models/post_image.rb
class PostImage < ApplicationRecord
  
   belongs_to :user
   
   attachment :image # ここを追加（_idは含めません）
   
   has_many :post_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   
   validates :shop_name, presence: true
  validates :image, presence: true
   

   def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
   end
   # favorited_by?メソッドを作成します。
   # このメソッドで、引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べます。
   # 存在していればtrue、存在していなければfalseを返すようにしています。
   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  
  # has_manyの後には、1:Nの関係になるモデル名を複数形で記述
  has_many :post_comments, dependent: :destroy
  # dependent: :destroyは、has_manyで使えるオプション   1:Nの関係において、「1」のデータが削除された場合、関連する「N」
  # この設定では、Userのデータが削除されたとき、そのUserが投稿したコメントデータも一緒に削除  
  
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  # attachmentには、カラム名（profile_image_id）から_idを除いた名前（profile_image）を記述します

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!,except: [:top]
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  # configure_permitted_parametersでは、devise_parameter_sanitizer.permitでnameのデータ操作を許可するアクションメソッドが指定されています。
# 今回のケースでは、ユーザ登録（sign_up）の際に、ユーザ名（name）のデータ操作が許可されます。
  
  
  def after_sign_in_path_for(resource)
    post_images_path
  end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
  
  # いいね機能も、indexアクションやnewアクションは作成しません。
  # コメント機能同様、投稿画像の詳細画面（/post_image/:id/）で実装します。
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    
    
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end
  # 投稿されたコメントを保存した後は、post_image_path(post_image)へリダイレクトされるように設定
  

  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to post_image_path(params[:post_image_id])
    
  end
  
end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end


# indexアクションやnewアクションは作成しません。
# つまり、コメント投稿だけの一覧画面や投稿画面は作成せず、その代わり、投稿画像の詳細画面（/post_image/:id/）にコメント投稿機能を実装します。

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  
  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
    
  end

  def index
    @post_images = PostImage.page(params[:page]).reverse_order
  end
  # indexアクションの中では、postimagesテーブル内の全データが取得されていました。=====>@post_images = PostImage.all
  # これを、1ページ分の決められた数のデータだけを、新しい順に取得するように変更しています。=======>
  # pageメソッドは、kaminariをインストールしたことで使用可能になったメソッドです。
  
  

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end


  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end
  
  
  # 投稿データのストロングパラメータ
  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])  
    @post_images = @user.post_images.page(params[:page]).reverse_order
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
   private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
          <!--navbar=====>ナビゲーションバーの表示,
          navbar-expand-lg=======>>指定した画面幅に応じてナビゲーションバー、ナビゲーションアイコンを切り替えて表示,
          navbar-light========>>カラースキームの指定-->
          
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <!--ここで配色を指定していないと要素はあるけど、見えない可能性がある-->
          <!--navbar-brand　　　　ロゴに使用されるnavbarのサポートclass-->
          <!--p-3でpaddingを-->
          
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_images/_list.html.erb
<div class="card-list-container py-5">
  <% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    
    
    
    <%= link_to post_image_path(post_image.id) do %>
      <%= attachment_image_tag post_image, :image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/post_images/index.html.erb
<%= render 'post_images/list', post_images: @post_images %>

<!--%= render [部分テンプレートファイルの指定], [ローカル変数]:[渡す値] %-->

<!--【テンプレートファイルを呼び出す記述】

部分テンプレートファイルを呼び出すには、renderを使う
'post_images/list'で部分テンプレートのパス（app/viewsより下のパス）を記述する
その際、アンダースコアと拡張子は省略する
ローカル変数（'post_images'）に渡すインスタンス変数（@post_images）を指定する-->

app/views/post_images/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <%= @post_image.errors.count %>件のエラーが発生しました
          <% @post_image.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @post_image, local:true do |f| %>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div>
  <%= attachment_image_tag @post_image, :image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <!--新しいメソッドが出てきました。投稿日付の形式を変換しているメソッド-->
  <!--'%Y/%m/%d'の記述で、年/月/日のフォーマットへ変換します。
　　　%Y、%m、%dは、日時のフォーマット指定によく使われます-->
　　　
　  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
  <% end %>
  <!---->
  
</div>

  <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

<div>
<p>コメント件数：<%= @post_image.post_comments.count %></p>
<% @post_image.post_comments.each do |post_comment| %>
  <p><%= image_tag('sample-author1.jpg') %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  
  
  <% if post_comment.user == current_user %>
  <div>
    <%= link_to "削除", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete %>
  </div>
  <% end %>
  <!--コメントしたものがログインユーザーのものであれば削除ボタンを表示して、削除できるようにしました。
      削除後は投稿詳細へリダイレクトされます。-->
  
<% end %>



</div>

<div>
<%= form_with(model:[@post_image, @post_comment], local: true) do |f| %>
<!--form_withに対して、[@post_image,@post_comment]のように、配列でインスタンス変数を2つ指定している点に注意してください。
コメントは、post_imageに結びついたpost_commentにあるため、2つ用意する必要があります。
また、post_commentをcreateするためのリクエストは、ルーティングもネスト（親子関係）しているため、上記2つの情報が必要になります。-->
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user, local:true do |f| %>



  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  
  
  
  
  
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <!--attachment_image_tagは、画像を埋め込むときに使います。これにより、ユーザのプロフィール画像が表示されます-->
  
  
  
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  <!--attachment_fieldで、画像選択用のボタンが生成されます。-->


  
  
  
  <%= f.submit "変更を保存" %>
<% end %>


<!--form_withでは、さきほどのインスタンス（@user）を使います。
text_fieldで、nameカラムを変更できるようにしています。-->

app/views/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <!---->
  
  <% if @user.id == current_user.id %>
  <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
  
</div>

<%= render 'post_images/list', post_images: @post_images %>
<!--部分テンプレートの呼び出し-->